server:
  port: 8081
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        # 服务注册中心地址
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1/demodb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: meihao2023
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml
